apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: gpt2
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: gpt2
    security.opendatahub.io/enable-auth: 'true'
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: caikit
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 4Gi
          nvidia.com/gpu: '1'
      runtime: gpt2
      storage:
        key: aws-connection-minio-data-connection
        path: caikit/
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule